// Generated by CoffeeScript 1.8.0
(function() {
  var frijControllers;

  frijControllers = angular.module('frij.controllers', []);

  frijControllers.controller('utilityListController', [
    '$scope', '$state', '$stateParams', 'UtilityChargePeriod', 'months', 'navControls', function($scope, $state, $stateParams, utilityAmounts, months, navControls) {
      var changeState;
      $scope.utilAmounts = utilityAmounts.data();
      $scope.balance = function() {
        var total, util, _i, _len, _ref;
        total = 0;
        _ref = $scope.utilAmounts;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          util = _ref[_i];
          total += parseFloat(util.amount);
        }
        return total;
      };
      $scope.save = function() {
        return utilityAmounts.update();
      };
      changeState = function(date) {
        return $state.go('utilityList', {
          year: date.getFullYear(),
          month: date.getMonth() + 1
        });
      };
      $scope.next = function() {
        return changeState(navControls.nextDatePeriod);
      };
      $scope.prev = function() {
        return changeState(navControls.prevDatePeriod);
      };
      $scope.monthName = function() {
        return months[parseInt($stateParams.month) - 1];
      };
      $scope.hasNext = function() {
        return navControls.hasNext;
      };
      $scope.hasPrev = function() {
        return navControls.hasPrev;
      };
      return $scope.testVar = 'test!';
    }
  ]);

}).call(this);

//# sourceMappingURL=controllers.js.map
